# Generated by Django 5.2.5 on 2025-08-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('input', 'INPUT'), ('output', 'OUTPUT')], max_length=6)),
                ('amount', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('action_datetime', models.DateTimeField()),
            ],
        ),
    ]
